// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFUbszY1wTDTNfjW_M0UNre-0t0ph1dE',
    appId: '1:527328432079:web:91f1d8efb23b2e8622ccba',
    messagingSenderId: '527328432079',
    projectId: 'qr-app-2fea4',
    authDomain: 'qr-app-2fea4.firebaseapp.com',
    storageBucket: 'qr-app-2fea4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN_cYpmR8sUlJKwWHgtxZa8YTnEjRZDlk',
    appId: '1:527328432079:android:1359a856457efcda22ccba',
    messagingSenderId: '527328432079',
    projectId: 'qr-app-2fea4',
    storageBucket: 'qr-app-2fea4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6TdJHGp9HWgMD5ANCyn2oL9n9vcBt1Ww',
    appId: '1:527328432079:ios:b1e32b0ad68771d622ccba',
    messagingSenderId: '527328432079',
    projectId: 'qr-app-2fea4',
    storageBucket: 'qr-app-2fea4.appspot.com',
    iosBundleId: 'com.example.qrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6TdJHGp9HWgMD5ANCyn2oL9n9vcBt1Ww',
    appId: '1:527328432079:ios:b1e32b0ad68771d622ccba',
    messagingSenderId: '527328432079',
    projectId: 'qr-app-2fea4',
    storageBucket: 'qr-app-2fea4.appspot.com',
    iosBundleId: 'com.example.qrApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcFUbszY1wTDTNfjW_M0UNre-0t0ph1dE',
    appId: '1:527328432079:web:6c51093c2b61320922ccba',
    messagingSenderId: '527328432079',
    projectId: 'qr-app-2fea4',
    authDomain: 'qr-app-2fea4.firebaseapp.com',
    storageBucket: 'qr-app-2fea4.appspot.com',
  );
}
